#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
VERSION=$(git log -1 --date="format:%Y.%m.%d.ai%j%H" --format="%cd")
echo "Version: $VERSION"
echo "Image Name: $IMAGE_NAME"
echo "Using BUILD_INFO=${BUILD_INFO}"
lscpu || /bin/true
free -m || /bin/true
docker buildx build \
	--load \
	--progress plain \
	--platform linux/arm64 \
	--build-arg OPENSCAD_VERSION="${VERSION}" \
	-f $DOCKERFILE_PATH -t $IMAGE_NAME .
